{
 "title": "Jaeger Collector",
 "description": "Dashboard for monitoring jaeger-collector running in a k8s environment.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_ns", "label": "k8s_ns", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Spans Received/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_received_total{namespace=~\"$k8s_ns\"}[5m])) by (namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Average in-queue latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_in_queue_latency_sum{namespace=~\"$k8s_ns\"} / jaeger_collector_in_queue_latency_count{namespace=~\"$k8s_ns\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Queue Length (Spans)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_queue_length{namespace=~\"$k8s_ns\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Spans Dropped/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jaeger_collector_spans_dropped_total{namespace=~\"$k8s_ns\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Batch Size (spans)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_batch_size{namespace=~\"$k8s_ns\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Span save latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_save_latency_sum{namespace=~\"$k8s_ns\"} / jaeger_collector_save_latency_count{namespace=~\"$k8s_ns\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  }
 ]
}