{
 "title": "Quack detailed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "serviceName", "label": "serviceName", "query": "prochain-startatlas-api" }
  ]
 },
 "panels": [
  { "title": "Main metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pm2_app_instances{serviceName=\"$serviceName\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Usage Max By any Instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(pm2_app_pids_cpu_threshold{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pm2_app_pids_memory{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(pm2_app_pids_memory{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests count/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_app_requests_total{serviceName=\"$serviceName\"}[1m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(nodejs_app_requests_active{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM2: Requests count\\sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pm2_http{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "{{__host__}}"
    }
   ]
  },
  {
   "title": "PM2: Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(pm2_active_requests{serviceName=\"$serviceName\"}) by (host)",
     "legendFormat": "{{__host__}}"
    }
   ]
  },
  { "title": "Pages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Load pages percentile 99p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nodejs_app_page_execute_bucket{serviceName=\"$serviceName\", code=\"200\"}[1m])) by (page, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load pages percentile 75p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nodejs_app_page_execute_bucket{serviceName=\"$serviceName\", code=\"200\"}[1m])) by (page, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages count\\sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_app_page_execute_count{serviceName=\"$serviceName\",code=\"200\"}[5m])) by (page)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP codes count\\sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_app_page_execute_count{serviceName=\"$serviceName\"}[5m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404 Pages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_app_page_execute_count{serviceName=\"$serviceName\",code=\"404\"}[10m])) by (page)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}