apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-cpu-utilization-configmap
  labels:
    my_custom_grafana_alert: "1"
data:
  alert-cpu-utilization.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: 5mn
          folder: Kubernetes Custom
          interval: 5m
          rules:
            - uid: belurur3frojkb
              title: CPU Utilization by namespace "prochain-staratlas"
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 21600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    adhocFilters: []
                    datasource:
                        type: prometheus
                        uid: prometheus
                    editorMode: builder
                    expr: sum by(namespace) (rate(container_cpu_usage_seconds_total{namespace=~"prochain-staratlas"}[$__rate_interval]))
                    instant: true
                    interval: ""
                    intervalMs: 30000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 2
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              dashboardUid: e1RXnCbVz
              panelId: 16
              noDataState: NoData
              execErrState: Error
              for: 5m
              annotations:
                __dashboardUid__: e1RXnCbVz
                __panelId__: "16"
                description: |-
                    MON URL:
                    https://rancher.atlassistant.com/dashboard/c/local/explorer/apps.deployment/prochain-staratlas/staratlas-api-app#pods
                runbook_url: https://rancher.atlassistant.com/dashboard/c/local/explorer/apps.deployment/prochain-staratlas/staratlas-api-app#pods
                summary: CPU HIGHER THAN 0.1
              labels: {}
              isPaused: false
              notification_settings:
                receiver: Notifications Daniel & Alex

