apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-kiali
  namespace: argo
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./kiali
    repoURL: https://github.com/danmgs/argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Replace=true
