{
 "title": "[Daniel] prochain-staratlas",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nombre total de redémarrages par pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"prochain-staratlas\", container=\"staratlas-api\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suivi des redémarrages par pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"prochain-staratlas\", container=\"staratlas-api\"}[1m])) by (pod)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD Container Max memory usage recorded in MiB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "floor(container_memory_max_usage_bytes{namespace=\"prochain-staratlas\", container=~\"staratlas-api.*\"} / 1024 / 1024)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD container_memory_usage in MiB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "floor(container_memory_usage_bytes{namespace=\"prochain-staratlas\", pod=~\"staratlas-api.*\"}/ 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD container_cpu_usage_seconds_total millicore",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"prochain-staratlas\", pod=~\"staratlas-api.*\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}